### ISSUE TITLE
Problem with the install method

### ISSUE THREAD

**Issue by jeffchulg** [artur-gajewski/FileBank#1]
Hi, i'm interested in this ZF module it seems to be quite good. The problem I have is that your way to install it requires the installation of all its dependencies inside the module... (if I have well understood).. 

I tried to add :

"require" : {
        "artur-gajewski/FileBank":"dev-master"
}
to the composer.json file of my app... But no way ! I get this message : 
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package artur-gajewski/filebank master could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

**Comment by ghost** [comment]
Same problem as me. Is there a workaround for this kind of problems ?

**Comment by artur-gajewski** [comment]
Ok, I have now fixed the problem composer can now be used to install FileBank.

"require" : {
     "artur-gajewski/file-bank":"dev-master"
}

Sorry for inconvenience, I never added this repository to Packagist, hence it was impossible to add it to composer.json without errors.

**Comment by artur-gajewski** [comment]
@jeffchulg and @Terrahawk

**Comment by ghost** [comment]
Thx. Works fine now :)

**Comment by valeriogalano** [comment]
Hi, I still have problem. This is my config:

```
"require": {
    "php": ">=5.3.3",
    "zendframework/zendframework": "2.*",
    "doctrine/doctrine-module": "0.*",
    "doctrine/doctrine-orm-module": "0.*",
    "artur-gajewski/file-bank":"dev-master"
}
```

Error:

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for artur-gajewski/file-bank dev-master -> satisfiable by artur-gajewski/file-bank dev-master.
    - artur-gajewski/file-bank dev-master requires doctrine/doctrine-orm-module dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by valeriogalano** [comment]
Installation works if I set doctrine-orm-module and zendframework packages to "dev-master" version.

It whould be great to use it on stable versions.

Thanks

**Comment by artur-gajewski** [comment]
@daredevel Sorry for getting back this late. For some reason I'm not getting emails about these replies.

Anyway, I updated the json file to reflect stable versions of doctrine-orm and zend framework and tried to install FileBank, installation was ok.
